### PR TITLE
Replace threetenabp with java 8 version using desugaring

### PR DESCRIPTION
**Pull request by ThePromoter**
First off, amazing library - thanks for creating and maintaining it!

I'm currently using a forked version with a few minor changes, but figured I would submit a PR back to you just in case my changes were of interest.  This PR has 2 things I've changed in it.

First and most importantly, it replaces threetenabp in favor of java8's `java.time` API by using the method described in more detail here https://developer.android.com/studio/write/java8-support

The second very minor change is a fix to `scrollToMonth` so that it uses `LinearLayoutManager.scrollToPositionWithOffset` with an offset of 0 instead of `scrollToPosition`.  When using `scrollToPosition`, it is not guaranteed that it ends with the specified position at the very top of the screen.  Passing an offset of 0 does guarantee this, and matches the behavior I personally needed (jump to a specific month with that month at the very top of the view).

Thanks again for all your hard work, and hopefully you find these changes valuable!

### CODE REVIEW

**Comment by kizitonwose** [comment]
Thank you very much for submitting this PR. I have been considering migrating to java.time via desugar but haven't followed through with it since it's going to be a breaking change. 

I guess since it's just imports that need to be updated, it shouldn't be a big issue. 

I noticed you bumped the library's min SDK from `15` to `21`, any reason for that?

**Comment by ThePromoter** [comment]
To be honest I only bumped it because that's the minSDK my app uses, and I originally only planned to fork and use my own copy, so I figured why not. I haven't tested to see if it all works when leaving the minSDK at 15, but assuming it still does then no reason to include that change!

**Comment by kizitonwose** [comment]
Oh, okay. I guess we'll keep it at 15 then.

I'll leave this PR open for a week or two just to see if there will be any input from others on the downsides of using desugar over ThreeTenABP.

If nothing comes up, I'll merge it.

**Comment by koral--** [comment]
References to ThreetenBP should be also removed from readme and `CalendarViewApp` from sample project can be removed entirely.

**Comment by kizitonwose** [comment]
> References to ThreetenBP should be also removed from readme and `CalendarViewApp` from sample project can be removed entirely.

Yep, I made mental notes to make those changes before actually publishing a release. The setup instructions in the readme needs a complete rewrite.

**Comment by HichamBI** [comment]
Great library ! Thanks for the hard work.
@kizitonwose  when did you plane to merge this PR and release a new version ?

**Comment by kizitonwose** [comment]
> when did you plane to merge this PR and release a new version ?

[Done!](https://github.com/kizitonwose/CalendarView/releases/tag/0.4.0) 🚀

**Pull request merged**
