### PR TITLE
Add Jalali(Shamsi/Hijri) Calendar support

### PR DESCRIPTION
**Pull request by sma6871**
I add some helper classes to support Jalali(Hijri/Shamsi) calendar which used in Iran/Afghanistan.
Furthermore, I provide an example to show developers, who want to implement Jalali calendar in their apps, how it would be used.
Moreover, **CalendarView** tests are updated to cover Jalali calendar.

You can Read more about [Jalali/Hijri calendar](https://en.wikipedia.org/wiki/Solar_Hijri_calendar).(This link is also added to ReadMe)

### CODE REVIEW

**Comment by kizitonwose** [comment]
Thank you very much for contributing! This is a huge change and I would have preferred that we discussed it before implementation, unless of course, you made the changes for personal use in your project and just wants to update the upstream.

In any case, I'm not sure how to move forward with this PR, mainly because I don't fully understand how the Hijri calendar works. I've read the linked wiki but my knowledge in this area is still not enough to maintain this feature if it gets merged.

I will not merge this PR, but if you are going to maintain your fork with this feature, I can link it in this repo's README so people who need it can easily find it.

**Comment by sma6871** [comment]
Thanks for your attention
Reasonable idea to link my repo to main README, it's my pleasure.
However, if you want to know more about Hijri Calendar, I'll tell you more.

**Comment by kizitonwose** [comment]
> However, if you want to know more about Hijri Calendar, I'll tell you.

Yes, please go ahead. I'm always open to learning.

**Comment by sma6871** [comment]
OK, sure
Hijri calendar is an astronomy calendar which contains 2 types: 
- **Solar** which is used in Iran and I implemented in this library 
- **Lunar** which is used in most of arabic countries

**Solar calendar** consists of 12 months, the first six of which are 31 days, the next five 30 days, and the final month 29 days in a normal year and 30 days in a leap year.

These are some notes to know what is the difference between Gregorian and Solar date:
* Solar year starts March 21st in normal years.
* There are 621/622 years difference between Solar and Gregorian date (i.e 2020=1398+622)
* Both of them are based on how many days will long for sun to cycle around the earth.

To implement more accurate calendar, I used an old and valid [library](https://github.com/mortezaadi/persian-calendar), which is extended from default [GregorianCalendar](https://docs.oracle.com/javase/7/docs/api/java/util/GregorianCalendar.html), to calculate Solar(persian) date based on [Julian date](https://en.wikipedia.org/wiki/Julian_day) which mainly used in all important softwares to calculate difference between two event.

This was a simple summary about Solar calendar, but it's calculations are too complicated and is one of the most accurate calendars in the world.

I hope this was helpful :)

**Comment by kizitonwose** [comment]
I definitely learned A LOT. Thank you!

**Comment by kizitonwose** [comment]
Guess I can close this PR now. If you have everything set up on your repo, let me know and I'll link it here. Cheers.

**Comment by sma6871** [comment]
Thank you for your attention.
Yes I did. I will be glad if you link it  to your repo :)

**Comment by kizitonwose** [comment]
@sma6871 You need to update the installation guide in your README to point to your repo. Your project can't be pulled in its current state.

**Comment by sma6871** [comment]
Hi again dude
Sorry for my mistake, I forgot to update some info but I did it now.

**Pull request closed without merging**
