### PR TITLE
Add fixed grid count to only show 7days

### PR DESCRIPTION
**Pull request by NelzkieCoder**
Add an option to choose if want to have a set fix grid count on adapter.

### CODE REVIEW

**Comment by kizitonwose** [comment]
Thanks for contributing! What is the use case for not having the fixed width?

**Comment by NelzkieCoder** [comment]
> Thanks for contributing! What is the use case for having the fixed width?

I have an app that needed the calendar to be inside a dialog. For UI design it does not look good and confusing sorry. So I thought adding an option for fixed width would be good.

**Comment by kizitonwose** [comment]
Could you show a visual representation of this(screenshot maybe)?

**Comment by NelzkieCoder** [comment]
> Could you show a visual representation of this(screenshot maybe)?

Hello. Here is the screenshot [](https://postimg.cc/LgpvXvnt)

**Comment by kizitonwose** [comment]
I see, how does the fix make it look now?

**Comment by NelzkieCoder** [comment]
> I see, how does the fix make it look now?

Here's what it looks with the fix 
[](https://postimg.cc/HrnZR0NC)

**Comment by kizitonwose** [comment]
Using Example 5, I am able to achieve the same result this way:

```kotlin
val size = 120
binding.exFiveCalendar.daySize = Size(size, size)
binding.exFiveCalendar.updateLayoutParams<ViewGroup.MarginLayoutParams> { width = size * 7 }
```

**Comment by NelzkieCoder** [comment]
> Using Example 5, I am able to achieve the same result this way:
> 
> ```kotlin
> val size = 120
> binding.exFiveCalendar.daySize = Size(size, size)
> binding.exFiveCalendar.updateLayoutParams<ViewGroup.MarginLayoutParams> { width = size * 7 }
> ```
> 
> 

Awesome. Then you can closed this if you want.

**Pull request closed without merging**
