### PR TITLE
make it backword compatible by using utilities from ViewCompat

### PR DESCRIPTION
**Pull request by adilo**

### CODE REVIEW

**Comment by kizitonwose** [comment]
I don't see any value in supporting these old devices which have like 1.5%(API 15 + 16) distribution. I'll still accept the PR with just the calls to `ViewCompat` but not the min sdk decrease.

**Comment by adilo** [comment]
Nowadays, it's better to be as inclusive as possible without breaking your core values. 1.5% percentage considering the number of devices worldwide, that's a big number. I always think about the emerging countries, people in need to use your app, but can't afford to switch to medium/high specs phone. They must be served well too. Not changing the min sdk is something that I don't recommend.

**Comment by kizitonwose** [comment]
I don't think anyone with a device running 4.0 or 4.1 right now has any interest in running apps on such a device.
That said, if this is something you really want, you can keep a fork with the SDK you desire which should be easy to keep in sync with the main repo.

**Comment by adilo** [comment]
How do you know ?

Anyway, thanks for accepting the changes. I won't be using my fork. Instead, I'll just use tools:overrideLibrary.

**Comment by kizitonwose** [comment]
> I'll just use tools:overrideLibrary.

Okay, that works too.

Will merge when the sdk-related changes are removed.

**Comment by kizitonwose** [comment]
Thank you for contributing!

**Pull request merged**
