### PR TITLE
Call super.onMeasure() before custom CalendarView logic

### PR DESCRIPTION
**Pull request by mcezat**

### CODE REVIEW

**Comment by mcezat** [comment]
This change appears to have fixed https://github.com/kizitonwose/CalendarView/issues/69

**Comment by carterhudson** [comment]
> This change appears to have fixed #69

The fix mentioned in #69 works for me. The fix on your fork, however, does not.

**Comment by kizitonwose** [comment]
@mcezat If you run the sample project using this setup, you can see that examples 3 and 5 are broken. This is because if `autoSize` is `true`(and it is by default), the CalendarView needs the View holders to size themselves first so it can then take the size of the visible view holder. So calling `super.onMeasure` earlier breaks this as the calendar sizes itself first before the view holders.

**Comment by mcezat** [comment]
Bah - that is unfortunate. At first glance it looked like nothing was broken after my change but looking more closely, you're right. Let me know investigate a little more and see what can be done.

**Pull request closed without merging**
